[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"

# Pretty URLs without .html extension
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/after"
  to = "/after.html"
  status = 200

[[redirects]]
  from = "/plan"
  to = "/plan.html"
  status = 200
